bld:
  commons:
    check:
      annotation: true
    resource:
      path:
        xls: /excel/Copertina.xls
        xlsx: /excel/Copertina.xlsx
    date:
      format: dd/MM/yyyy
    report:
      excel:
        titolo: A12
        date: A18



autore-libri-row:
  nome:
    name-column: Nome
  matricola:
    name-column: Matricola
  cognome:
    name-column: Cognome



logging:
  level:
    org:
      springframework: INFO

#logging:
#  level:
#    root: WARN
#    org:
#      springframework:
#        web: DEBUG
#      hibernate: ERROR


server:
  port: 8080


